/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiMeaasge: typeof import('./src/components/h5Components/Message/AiMeaasge.vue')['default']
    copy: typeof import('./src/components/h5Components/Message/AiMeaasge copy.vue')['default']
    FaTextarea: typeof import('./src/components/base/fa-textarea/index.vue')['default']
    FsTextarea: typeof import('./src/components/base/FsTextarea/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icon: typeof import('~icons/ic/on')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserMessage: typeof import('./src/components/h5Components/Message/UserMessage.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
  }
}
